### ISSUE TITLE
Llama2-fine_tuning-Lora - peft - ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' 

### ISSUE THREAD

**Issue by jaglinux** [jaglinux/huggingface-projects#1]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/envs/py_3.10/lib/python3.10/site-packages/bitsandbytes-0.39.1-py3.10.egg/bitsandbytes/libbitsandbytes_hip_nohipblaslt.so
CUDA SETUP: Loading binary /opt/conda/envs/py_3.10/lib/python3.10/site-packages/bitsandbytes-0.39.1-py3.10.egg/bitsandbytes/libbitsandbytes_hip_nohipblaslt.so...
Traceback (most recent call last):
  File "./Llama2-FineTuning-Lora.py", line 10, in <module>
    from trl import SFTTrainer
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/trl/__init__.py", line 6, in <module>
    from .extras import BestOfNSampler
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/trl/extras/__init__.py", line 16, in <module>
    from .best_of_n_sampler import BestOfNSampler
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/trl/extras/best_of_n_sampler.py", line 7, in <module>
    from ..models import SUPPORTED_ARCHITECTURES, PreTrainedModelWrapper
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/trl/models/__init__.py", line 16, in <module>
    from .modeling_base import PreTrainedModelWrapper, create_reference_model
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/trl/models/modeling_base.py", line 29, in <module>
    from peft import (
ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft' (/opt/conda/envs/py_3.10/lib/python3.10/site-packages/peft/__init__.py)

**Comment by jaglinux** [comment]
pip install trl <to latest package version>
